### ISSUE TITLE
Use HTTPS-only for serving pm2 site and docs

### ISSUE THREAD

**Issue by davidjb** [pm2-hive/pm2-hive.github.io#133]
At present, HTTPS serving is available and working for the pm2 docs at https://pm2.keymetrics.io/ but the site is served over insecure HTTP by default (http://pm2.keymetrics.io/)

As Firefox/Chrome etc continue to mark more uses of HTTP as insecure ([Chrome](https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure), [Firefox](https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/)), it would be great if the docs could switch to being HTTPS-only -- eg doing a 301 redirect to HTTPS by default + sending HSTS headers etc.

Since HTTPS is already up and working for you with Let's Encrypt, the change wouldn't be a major one.

**Comment by vmarchaud** [comment]
We are re-working on the documentation and the next release will be done only over HTTPS.
Note that we currently the doc is hosted on github pages so we can't manage that ourselves sadly
