### ISSUE TITLE
pm2-api page has bad formatting of bullet points

### ISSUE THREAD

**Issue by fresheneesz** [pm2-hive/pm2-hive.github.io#26]
If you look at this page: http://pm2.keymetrics.io/docs/usage/pm2-api/ , you can see places where bullet points are not rendered, but instead displayed as inline astrisks, even tho the page is properly formatted here: https://github.com/pm2-hive/pm2-hive.github.io/blob/master/docs/features/pm2-api.md

**Comment by fresheneesz** [comment]
@vmarchaud Why did you close this? This isn't fixed.

**Comment by vmarchaud** [comment]
mb i was thinking about another issue

**Comment by fresheneesz** [comment]
Thanks

**Comment by vmarchaud** [comment]
Fixed now

**Comment by fresheneesz** [comment]
@vmarchaud Thanks! What was the problem? Also, there are still some unrendered astrisks on pm2.list, pm2.dump, and 5 or 6 others directly under those.

**Comment by vmarchaud** [comment]
@fresheneesz Done, problem come from missing newline between text and parameters (weird parsing of markdown i guess)

**Comment by fresheneesz** [comment]
Gotcha, thanks!
