### ISSUE TITLE
Need an example for restart...

### ISSUE THREAD

**Issue by ScriptPup** [pm2-hive/pm2-hive.github.io#39]
Hi, I've tried using the pm2 api to restart my app from within itself, but can't get it to work. This is what I have : 
```
pm2.connect(function(err){
                    pm2.list(function(err,proc){
                        var procs = new Array();
                        for(var i=0; i < proc.length; i++){
                            if(proc[i].name !== 'LabMan_ADMIN'){
                                procs.push(proc[i]);
                                //pm2.restart(proc[i]);  
                            }           
                        } 
                        pm2.disconnect();
                        pm2.restart(procs[0],function(err, proc){
                            console.error("Error restarting proc");
                            console.error(err);
                            console.error(proc);
                        });
                    });
                });
```

Clearly I've got something wrong (yes I know that procs[0] is only going to restart 1... Or it would... It was part of my testing.

I tried using the name, the id... nothing seems to work. 

Thank you for any help you have!

**Comment by vmarchaud** [comment]
Example in the [API unit test](https://github.com/Unitech/pm2/blob/master/test/programmatic/programmatic.js#L225), the problem is that you disconnected before sending the request to restart, that will not work.
