### ISSUE TITLE
Update the heroku documentation

### ISSUE THREAD

**Issue by Unitech** [pm2-hive/pm2-hive.github.io#85]
Edit this page: http://pm2.keymetrics.io/docs/usage/use-pm2-with-cloud-providers/ (or add a new one)

# New way of installing pm2 in heroku

1/ In the package.json in the [preinstall directive](https://docs.npmjs.com/misc/scripts), add "npm install pm2 -g"
2/ In the Procfile in the start attribute do "pm2 start ecosystem.config.js"

Done! Much simpler than what is explained there: http://pm2.keymetrics.io/docs/usage/use-pm2-with-cloud-providers/

**Comment by alavit-d** [comment]
Done, might be interesting to do exhaustive review of different cloud providers to see if -g is avalaible everywhere

**Comment by Unitech** [comment]
LGTM! closing
