### ISSUE TITLE
Watch can be a boolean, an array of paths or a string representing a path. Can it?

### ISSUE THREAD

**Issue by mitselek** [pm2-hive/pm2-hive.github.io#98]
https://github.com/pm2-hive/pm2-hive.github.io/blame/master/docs/features/watch-restart.md#L39
says:
> As specified in the Schema:
     watch can be a boolean, an array of paths or a string representing a path

but in Schema
https://github.com/pm2-hive/pm2-hive.github.io/blame/master/docs/features/app-declaration.md#L179
it says:

> |    Field |   Type  |  Example |  Description|
> |:----------|:-------:|:------------------------------:|:-------------------------|
> | watch   | boolean or [] |  true |  enable watch & restart feature, if a file change in the folder or subfolder, your app will get reloaded |

**Comment by vmarchaud** [comment]
From the [schema definition inside PM2](https://github.com/Unitech/pm2/blob/master/lib/API/schema.json#L109), it can be either a string, an array or a boolean
